#!/bin/bash

## TODO: <placeholder> will be rewritten with fpga regtbl way.

# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
#  NVIDIA CORPORATION and its licensors retain all intellectual property
#  and proprietary rights in and to this software, related documentation
#  and any modifications thereto.  Any use, reproduction, disclosure or
#  distribution of this software and related documentation without an express
#  license agreement from NVIDIA CORPORATION is strictly prohibited.

APP_NAME="hsc_alert_wrapper"
APP_VER="0.1"

show_help()
{
    echo "A wrapper for checking HSC alert status only when base power good is asserted, ver=${APP_VER}."
    echo "<usage>"
    echo "  ${APP_NAME} HSC_ID"
    echo
}

get_hsc_alert_state()
{
    echo "$data_out"
    return 0
}


## MAIN
if [ "$#" -ne 1 ]; then
    show_help
    exit 101
fi

get_hsc_alert_state "$@"
exit $?
